version: "3"

tasks:
  migrate:
    aliases:
      - mig
    desc: "Migrate database"
    cmds:
      - go run ./cmd/migrator/migrator.go --storage-path=./storage/sso.db --migrations-path=./migrations